package model;
// Generated 24.07.2018 14:18:10 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Category generated by hbm2java
 */
public class Category  implements java.io.Serializable {


     private int id;
     private String name;
     private boolean isIncome;
     private boolean isDeleted;
     private Set paymentses = new HashSet(0);

    public Category() {
    }

	
    public Category(int id, String name, boolean isIncome, boolean isDeleted) {
        this.id = id;
        this.name = name;
        this.isIncome = isIncome;
        this.isDeleted = isDeleted;
    }
    public Category(int id, String name, boolean isIncome, boolean isDeleted, Set paymentses) {
       this.id = id;
       this.name = name;
       this.isIncome = isIncome;
       this.isDeleted = isDeleted;
       this.paymentses = paymentses;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public boolean isIsIncome() {
        return this.isIncome;
    }
    
    public void setIsIncome(boolean isIncome) {
        this.isIncome = isIncome;
    }
    public boolean isIsDeleted() {
        return this.isDeleted;
    }
    
    public void setIsDeleted(boolean isDeleted) {
        this.isDeleted = isDeleted;
    }
    public Set getPaymentses() {
        return this.paymentses;
    }
    
    public void setPaymentses(Set paymentses) {
        this.paymentses = paymentses;
    }




}


