package model;
// Generated 27.07.2018 23:57:36 by Hibernate Tools 4.3.1

import java.util.HashSet;
import java.util.Set;

/**
 * Category generated by hbm2java
 */
public class Category  implements java.io.Serializable {


     private Integer id;
     private String name;
     private boolean isIncome;
     private boolean isDeleted;
     private Set paymentses = new HashSet(0);

    public Category() {
    }
	
    public Category(String name, boolean isIncome, boolean isDeleted) {
        this.name = name;
        this.isIncome = isIncome;
        this.isDeleted = isDeleted;
    }
    public Category(String name, boolean isIncome, boolean isDeleted, Set paymentses) {
       this.name = name;
       this.isIncome = isIncome;
       this.isDeleted = isDeleted;
       this.paymentses = paymentses;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public boolean isIsIncome() {
        return this.isIncome;
    }
    
    public void setIsIncome(boolean isIncome) {
        this.isIncome = isIncome;
    }
    public boolean isIsDeleted() {
        return this.isDeleted;
    }
    
    public void setIsDeleted(boolean isDeleted) {
        this.isDeleted = isDeleted;
    }
    public Set getPaymentses() {
        return this.paymentses;
    }
    
    public void setPaymentses(Set paymentses) {
        this.paymentses = paymentses;
    }
    
}


