package model;
// Generated 07.08.2018 10:24:17 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Person generated by hbm2java
 */
public class Person  implements java.io.Serializable {


     private Integer id;
     private String name;
     private boolean isDeleted;
     private Set fixpaymentses = new HashSet(0);
     private Set paymentses = new HashSet(0);

    public Person() {
    }

	
    public Person(String name, boolean isDeleted) {
        this.name = name;
        this.isDeleted = isDeleted;
    }
    public Person(String name, boolean isDeleted, Set fixpaymentses, Set paymentses) {
       this.name = name;
       this.isDeleted = isDeleted;
       this.fixpaymentses = fixpaymentses;
       this.paymentses = paymentses;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public boolean isIsDeleted() {
        return this.isDeleted;
    }
    
    public void setIsDeleted(boolean isDeleted) {
        this.isDeleted = isDeleted;
    }
    public Set getFixpaymentses() {
        return this.fixpaymentses;
    }
    
    public void setFixpaymentses(Set fixpaymentses) {
        this.fixpaymentses = fixpaymentses;
    }
    public Set getPaymentses() {
        return this.paymentses;
    }
    
    public void setPaymentses(Set paymentses) {
        this.paymentses = paymentses;
    }




}


