
package ws_client;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.11-b150120.1832
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "PDFGeneratorService", targetNamespace = "http://ws/", wsdlLocation = "http://localhost:1234/services?wsdl")
public class PDFGeneratorService
    extends Service
{

    private final static URL PDFGENERATORSERVICE_WSDL_LOCATION;
    private final static WebServiceException PDFGENERATORSERVICE_EXCEPTION;
    private final static QName PDFGENERATORSERVICE_QNAME = new QName("http://ws/", "PDFGeneratorService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:1234/services?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        PDFGENERATORSERVICE_WSDL_LOCATION = url;
        PDFGENERATORSERVICE_EXCEPTION = e;
    }

    public PDFGeneratorService() {
        super(__getWsdlLocation(), PDFGENERATORSERVICE_QNAME);
    }

    public PDFGeneratorService(WebServiceFeature... features) {
        super(__getWsdlLocation(), PDFGENERATORSERVICE_QNAME, features);
    }

    public PDFGeneratorService(URL wsdlLocation) {
        super(wsdlLocation, PDFGENERATORSERVICE_QNAME);
    }

    public PDFGeneratorService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, PDFGENERATORSERVICE_QNAME, features);
    }

    public PDFGeneratorService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public PDFGeneratorService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns PDFGenerator
     */
    @WebEndpoint(name = "PDFGeneratorPort")
    public PDFGenerator getPDFGeneratorPort() {
        return super.getPort(new QName("http://ws/", "PDFGeneratorPort"), PDFGenerator.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns PDFGenerator
     */
    @WebEndpoint(name = "PDFGeneratorPort")
    public PDFGenerator getPDFGeneratorPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://ws/", "PDFGeneratorPort"), PDFGenerator.class, features);
    }

    private static URL __getWsdlLocation() {
        if (PDFGENERATORSERVICE_EXCEPTION!= null) {
            throw PDFGENERATORSERVICE_EXCEPTION;
        }
        return PDFGENERATORSERVICE_WSDL_LOCATION;
    }

}
