
package ws;

import javax.jws.WebMethod;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.FaultAction;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.11-b150120.1832
 * Generated source version: 2.2
 * 
 */
@WebService(name = "PDFGenerator", targetNamespace = "http://ws/")
@SOAPBinding(style = SOAPBinding.Style.RPC)
@XmlSeeAlso({
    ObjectFactory.class
})
public interface PDFGenerator {


    /**
     * 
     * @throws IOException_Exception
     */
    @WebMethod
    @Action(input = "http://ws/PDFGenerator/createPDFRequest", output = "http://ws/PDFGenerator/createPDFResponse", fault = {
        @FaultAction(className = IOException_Exception.class, value = "http://ws/PDFGenerator/createPDF/Fault/IOException")
    })
    public void createPDF()
        throws IOException_Exception
    ;

}
